name: Build and execute py script

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fmatrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installation de python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Execution du script
      run: python main.py

    - name: Installation des d√©pendances
      run: pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

    - name: Execution des tests
      run: |
        pytest --cov=./ --cov-report=xml